"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROJEN_MARKER = exports.PROJEN_RC = void 0;
exports.PROJEN_RC = '.pjrc.js';
exports.PROJEN_MARKER = '~~ Generated by ' + 'miniprojen'; // we split into two so /this/ file does not match the marker
